services:
  slidev:
    build:
      dockerfile: slidev.Dockerfile
    volumes:
      - ./slidev:/app/slidev
    ports:
      - 3030:3030
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
